[build]
  functions = "backend/functions"
[functions]
  external_node_modules = ["express", "serverless-http"]
  included_files = ["backend/data.json"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/users/*"
  status = 200
  to = "/.netlify/functions/server"
