[functions]
  external_node_modules = ["express", "serverless-http"]
  functions = "backend/functions"
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/users/*"
  status = 200
  to = "/.netlify/functions/"
